// <auto-generated />
using System;
using ExpenseTrackerAPI.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerAPI.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    [Migration("20220120172005_Add_ModelBases")]
    partial class Add_ModelBases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.ModelBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedData")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedData")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ModelBases");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModelBase");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.OrderStatus", b =>
                {
                    b.HasBaseType("ExpenseTrackerAPI.EF.Models.ModelBase");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OrderStatus");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.PaymentMethod", b =>
                {
                    b.HasBaseType("ExpenseTrackerAPI.EF.Models.ModelBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethod_OrderId");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PaymentMethod");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.PurchaseTax", b =>
                {
                    b.HasBaseType("ExpenseTrackerAPI.EF.Models.ModelBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PurchaseTax_Description");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxRatePercent")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PurchaseTax");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.UOM", b =>
                {
                    b.HasBaseType("ExpenseTrackerAPI.EF.Models.ModelBase");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UOM_Discription");

                    b.Property<int>("InvoiceItemId")
                        .HasColumnType("int")
                        .HasColumnName("UOM_InvoiceItemId");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UOM");
                });

            modelBuilder.Entity("ExpenseTrackerAPI.EF.Models.UserAccount", b =>
                {
                    b.HasBaseType("ExpenseTrackerAPI.EF.Models.ModelBase");

                    b.Property<int?>("AccountingPeriod")
                        .HasColumnType("int");

                    b.Property<int?>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LenguageId")
                        .HasColumnType("int");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("UserAccount_OrderId");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UserAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
